# Generated by Django 4.0 on 2021-12-09 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_alter_bb_content_alter_bb_price_alter_bb_published_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bb',
            options={'ordering': ['-published'], 'verbose_name': 'announcement', 'verbose_name_plural': 'announcements'},
        ),
    ]
